/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misClases;

import java.io.IOException;
import misClases.Servidor;
import misClases.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author Eliba
 */
public class JFramePresentacionJuego extends javax.swing.JFrame {

    /**
     * Creates new form JFramePresentacionJuego
     */
    public JFramePresentacionJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPresentacionJuego = new javax.swing.JPanel();
        jButtonServidor = new javax.swing.JButton();
        jButtonJugador = new javax.swing.JButton();
        jButtonInstrucciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonServidor.setText("Servidor");
        jButtonServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServidorActionPerformed(evt);
            }
        });

        jButtonJugador.setText("Jugador");
        jButtonJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugadorActionPerformed(evt);
            }
        });

        jButtonInstrucciones.setText("Instrucciones");
        jButtonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstruccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPresentacionJuegoLayout = new javax.swing.GroupLayout(jPanelPresentacionJuego);
        jPanelPresentacionJuego.setLayout(jPanelPresentacionJuegoLayout);
        jPanelPresentacionJuegoLayout.setHorizontalGroup(
            jPanelPresentacionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentacionJuegoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButtonJugador)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPresentacionJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInstrucciones)
                .addGap(15, 15, 15))
        );
        jPanelPresentacionJuegoLayout.setVerticalGroup(
            jPanelPresentacionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPresentacionJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInstrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(jPanelPresentacionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonServidor)
                    .addComponent(jButtonJugador))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPresentacionJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPresentacionJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServidorActionPerformed
        // TODO add your handling code here:
        String nombreJugador1 = JOptionPane.showInputDialog("Introduce el nombre del jugador 1: ");
        //condiconal para impedir que no se introduzca el nombre 
        if(nombreJugador1 != null && !nombreJugador1.trim().isEmpty()){
            JFrameTablero tablero = new JFrameTablero(nombreJugador1, "servidor");
            tablero.setLocationRelativeTo(null);
            tablero.setSize(800, 600);
            tablero.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "El nombre es obligatorio");
        }
    }//GEN-LAST:event_jButtonServidorActionPerformed

    private void jButtonJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugadorActionPerformed
        // TODO add your handling code here:
        String nombreJugador2 = JOptionPane.showInputDialog("Introduce el nombre del jugaodr 2: ");
        //condiconal para impedir que no se introduzca el nombre
        if(nombreJugador2 != null && !nombreJugador2.trim().isEmpty()){
            JFrameTablero tablero = new JFrameTablero(nombreJugador2, "jugador");
            tablero.setLocationRelativeTo(null);
            tablero.setSize(800, 600);
            tablero.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "El nombre es obligatorio");
        }
    }//GEN-LAST:event_jButtonJugadorActionPerformed

    private void jButtonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstruccionesActionPerformed
        // TODO add your handling code here:
        JFrameInstrucciones instrucciones = new JFrameInstrucciones();
        instrucciones.setSize(600, 500);
        instrucciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInstruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePresentacionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePresentacionJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInstrucciones;
    private javax.swing.JButton jButtonJugador;
    private javax.swing.JButton jButtonServidor;
    private javax.swing.JPanel jPanelPresentacionJuego;
    // End of variables declaration//GEN-END:variables
}
