
package misClases;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.lang.String;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class JFramePersonaje extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel("/misClases/recursos/pWall.jpg");
    private String nombre;//recibe los nombres del jugador
    private String tipo;//recibe si el jugador es normal o jugador-servidor
    private String personaje;
    
    public JFramePersonaje() {
        initComponents();
    }
    
    public JFramePersonaje(String nombre, String tipo) {
        
        initComponents();
        generarTableroPersonajes();
        jPanel2.setOpaque(false);
        Pselect.setVisible(false); // Oculto
        this.tipo=tipo;
        this.nombre=nombre;
        
        lblPersonaje.setOpaque(true);
        cambiarIcono(jButton2, ControlMusica.estaPausada()
            ? "/misClases/recursos/playBtn.png"
            : "/misClases/recursos/pauseBtn.png");
        cambiarIcono(jButton1, "/misClases/recursos/regresa.png");
        
        if (!ControlMusica.estaPausada()) {
            ControlMusica.iniciarMusica("/misClases/recursos/MusicaInicio.wav");
        }
        
        generarTableroPersonajes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel("/misClases/recursos/pWall.jpg");
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Pselect = new javax.swing.JButton();
        lblPersonaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misClases/recursos/regresa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misClases/recursos/playBtn.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ELEGIR PERSONAJE POR TABLERO");

        jPanel2.setBackground(new java.awt.Color(33, 93, 149));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Pselect.setBackground(new java.awt.Color(226, 175, 2));
        Pselect.setFont(new java.awt.Font("Tempus Sans ITC", 1, 19)); // NOI18N
        Pselect.setText("Continuar");
        Pselect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        Pselect.setEnabled(false);
        Pselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PselectActionPerformed(evt);
            }
        });

        lblPersonaje.setBackground(new java.awt.Color(36, 94, 150));
        lblPersonaje.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        lblPersonaje.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(Pselect, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pselect, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ControlMusica.pausarReanudar();

        if (ControlMusica.estaPausada()) {
            cambiarIcono(jButton2, "/misClases/recursos/playBtn.png");
        } else {
            cambiarIcono(jButton2, "/misClases/recursos/pauseBtn.png");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();  
        JFrameMenu menu = new JFrameMenu(nombre, tipo);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PselectActionPerformed
        this.dispose();  
        JFrameTablero tablero = new JFrameTablero(nombre, tipo, personaje);
        tablero.setVisible(true);
    }//GEN-LAST:event_PselectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pselect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPersonaje;
    // End of variables declaration//GEN-END:variables

    private void cambiarIcono(javax.swing.JButton boton, String rutaImagen) {
        ImageIcon originalIcon = new ImageIcon(getClass().getResource(rutaImagen));
        Image img = originalIcon.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH);
        boton.setIcon(new ImageIcon(img));
    }
    
    private void generarTableroPersonajes() {
        // Paso 1: Lista de imágenes
        List<String> imagenes = new ArrayList<>();
        Collections.addAll(imagenes,
            "/misClases/recursos/personajes/Alcalde Quimby.png",
            "/misClases/recursos/personajes/Apu.png",
            "/misClases/recursos/personajes/Barney.png",
            "/misClases/recursos/personajes/Bart.png",
            "/misClases/recursos/personajes/Bruja Lisa.png",
            "/misClases/recursos/personajes/Capitan Horatio.png",
            "/misClases/recursos/personajes/Carl.png",
            "/misClases/recursos/personajes/Duffman.png",
            "/misClases/recursos/personajes/Evil Flanders.png",
            "/misClases/recursos/personajes/Funzo.png",
            "/misClases/recursos/personajes/Gato Marge.png",
            "/misClases/recursos/personajes/Hans Moleman.png",
            "/misClases/recursos/personajes/Herman.png",
            "/misClases/recursos/personajes/Heroe Milhouse.png",
            "/misClases/recursos/personajes/Homero.png",
            "/misClases/recursos/personajes/Kodos.png",
            "/misClases/recursos/personajes/Krusty.png",
            "/misClases/recursos/personajes/Lenny.png",
            "/misClases/recursos/personajes/Lisa.png",
            "/misClases/recursos/personajes/Maggie.png",
            "/misClases/recursos/personajes/Marge.png",
            "/misClases/recursos/personajes/Melvin.png",
            "/misClases/recursos/personajes/Milhouse.png",
            "/misClases/recursos/personajes/Moe.png",
            "/misClases/recursos/personajes/Nick Riviera.png",
            "/misClases/recursos/personajes/Otto.png",
            "/misClases/recursos/personajes/Patty.png",
            "/misClases/recursos/personajes/Payaso Rapha.png",
            "/misClases/recursos/personajes/Pica.png",
            "/misClases/recursos/personajes/Rasca.png",
            "/misClases/recursos/personajes/Selma.png",
            "/misClases/recursos/personajes/Snake.png",
            "/misClases/recursos/personajes/Sr Burns.png",
            "/misClases/recursos/personajes/Willie.png"     
        );

        // Paso 2: Barajar y tomar solo 24
        Collections.shuffle(imagenes);
        List<String> seleccionados = imagenes;

        // Paso 3: Configurar el panel
        jPanel2.removeAll();
        jPanel2.setLayout(new GridLayout(5, 7, 20, 20));



        // Paso 4: Crear y añadir los botones
        for (String ruta : seleccionados) {
            JButton boton = new JButton();

            // Icono
            java.net.URL url = getClass().getResource(ruta);
            if (url != null) {
                ImageIcon icono = new ImageIcon(url);
                Image imagen = icono.getImage().getScaledInstance(65, 85, Image.SCALE_SMOOTH);
                boton.setIcon(new ImageIcon(imagen));
            } else {
                boton.setText("No encontrada");
            }


            boton.setText(null); // Quita texto
            boton.setBorderPainted(false); // Quita borde
            boton.setContentAreaFilled(false); // Hace fondo transparente
            boton.setFocusPainted(false); // Quita el marco cuando se enfoca
            
            //String nombre = ruta.substring(ruta.lastIndexOf("/") + 1).replace(".jpg", "");
            // Acción cuando se elige
            /*boton.addActionListener(e -> {
                JOptionPane.showMessageDialog(this, "Seleccionaste a: " + nombre);
            });*/
            boton.addActionListener(e -> {
                String nombre = ruta.substring(ruta.lastIndexOf("/") + 1).replace(".png", "");
                personaje = nombre;
                lblPersonaje.setText("Seleccionaste a: " + personaje);
                Pselect.setVisible(true);   // Ahora aparece
                Pselect.setEnabled(true);   // Y se puede usar
            });
            
            jPanel2.add(boton);
        }

        jPanel2.revalidate();
        jPanel2.repaint();
    }

    
}

